@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")
@include("awscli")
@include("service_user")

COPY my_exec.sh /sbin/my_exec

RUN ${SYSTEM_UPDATE} \
 && ${PKG_INSTALL} postgresql-client jq \
 && ${SYSTEM_CLEANUP} \
 && chmod +x /sbin/my_exec

@include("copy-metadata")
@include("symlinks")
@include("instructions")

