defineEnvVar PARENT_IMAGE_TAG MANDATORY "The version of the parent image" "0.11";
defineEnvVar NEXUS_VERSION MANDATORY "The version of Sonatype Nexus" "3.13.0-01";
defineEnvVar TAG MANDATORY "The image tag" '${NEXUS_VERSION}';
defineEnvVar NEXUS_ARTIFACT MANDATORY "The Nexus artifact" 'nexus-${NEXUS_VERSION}-unix.tar.gz';
defineEnvVar NEXUS_DOWNLOAD_URL MANDATORY "The url to download Nexus from" 'https://download.sonatype.com/nexus/3/${NEXUS_ARTIFACT}';
defineEnvVar NEXUS_MIN_MEMORY MANDATORY "The minimal memory setting for Nexus" "1024m";
defineEnvVar NEXUS_MAX_MEMORY MANDATORY "The maximum memory setting for Nexus" "4096m";
defineEnvVar NEXUS_MAX_PERM_SIZE MANDATORY "The maxPermSize setting for Nexus" "192m";
defineEnvVar NEXUS_DEFAULT_VIRTUAL_HOST MANDATORY "The default virtual host for Nexus" 'nexus.${DOMAIN}';
defineEnvVar NEXUS_UI_HTTP_PORT MANDATORY "The default HTTP por for Nexus" "8081";
defineEnvVar NEXUS_UI_HTTPS_PORT MANDATORY "The default HTTPS por for Nexus" "8083";
defineEnvVar NEXUS_DOCKER_REGISTRY_PORT MANDATORY "The HTTPS port for the Docker registry" "18443";
defineEnvVar NEXUS_DOCKER_GROUP_PORT MANDATORY "The HTTPS port for the Dcoker group (proxy + registry)" "18444";
defineEnvVar NEXUS_WORK_FOLDER MANDATORY "The work folder used in Nexus" "/opt/sonatype/sonatype-work/nexus3";
defineEnvVar SERVICE_USER MANDATORY "The service user" "nexus";
defineEnvVar SERVICE_GROUP MANDATORY "The service group" "nexus";
defineEnvVar SERVICE_USER_HOME MANDATORY 'The home of the ${SERVICE_USER} user' '${NEXUS_WORK_FOLDER}';
defineEnvVar SERVICE_USER_SHELL MANDATORY 'The shell of the ${SERVICE_USER} user' '/bin/bash';
overrideEnvVar ENABLE_LOGSTASH MANDATORY "true";
# vim: syntax=sh ts=2 sw=2 sts=4 sr noet
