#!/bin/bash

set -a
NEXUS_HOME=/opt/sonatype/nexus
SONATYPE_WORK=/sonatype-work
KARAF_DATA=${SONATYPE_WORK}
SONATYPE_USER="nexus"

chown -R nexus:nexus ${SONATYPE_WORK}

sed -i "s/^-Xms(.*)$/-Xms${NEXUS_MIN_MEMORY:-${SQ_NEXUS_MIN_MEMORY}}/g" ${NEXUS_HOME}/bin/nexus.vmoptions
sed -i "s/^-Xmx(.*)$/-Xms${NEXUS_MAX_MEMORY:-${SQ_NEXUS_MAX_MEMORY}}/g" ${NEXUS_HOME}/bin/nexus.vmoptions
sed -i "s/^#run_as_user=(.*)/run_as_user=${SONATYPE_USER}/g" ${NEXUS_HOME}/bin/nexus.rc

_folder=${NEXUS_HOME}
_exports="$(export)";

cat << EOF > /tmp/runme
#!/bin/bash

${_exports}
declare -x HOME="/home/nexus"
cd ${_folder}
bin/nexus run
EOF
chmod +x /tmp/runme

chpst -u nexus:nexus -U nexus:nexus /tmp/runme

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
