@include("preamble")
FROM ${NAMESPACE}/jekyll:${TAG}
@include("maintainer")

@include("addon-toggles")

USER jekyll
WORKDIR /var/www/jekyll

RUN git clone https://github.com/${GITHUB_USER}/${GITHUB_USER}.github.io.git
COPY _config.yml /var/www/jekyll/_config.yml
COPY rc.local /etc/rc.local
RUN chmod +x /etc/rc.local

@include("copy-metadata")
@include("instructions")