@include("preamble")
FROM ${REGISTRY}/${NAMESPACE}/base:${TAG}
@include("maintainer")

@include("addon-toggles")

@include("java")
@include("service_user")
@include("tomcat")
@include("apr")

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE} && \
COPY tomcat-files/service /etc/service/${IMAGE}/run
RUN chmod +x /etc/service/${IMAGE}/run

EXPOSE 8080

@include("copy-metadata")
@include("instructions")
@include("symlinks")
