defineEnvVar PARENT_IMAGE_TAG "The version of the parent image" "201612";
defineEnvVar PACKETBEAT_VERSION "The packetbeat version" "1.3.1";
overrideEnvVar TAG '${PACKETBEAT_VERSION}';
overrideEnvVar ENABLE_LOGSTASH "false";
overrideEnvVar ENABLE_LOCAL_SMTP "false";
overrideEnvVar ENABLE_CRON "false";
overrideEnvVar ENABLE_RSNAPSHOT "false";
overrideEnvVar ENABLE_SYSLOG "false";
defineEnvVar SERVICE_USER "The service user" "packetbeat";
defineEnvVar SERVICE_GROUP "The group of the service account" "packetbeat";
