@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")
@include("addon-toggles")
@include("service_user")
@include("service")
@include("metricbeat")

ENV ELASTICSEARCH_HOST="elasticsearch" \
    ELASTICSEARCH_PORT="9200"

COPY packetbeat.yml /etc/packetbeat/packetbeat.yml

VOLUME /backup/${IMAGE}/data

@include("copy-metadata")
@include("symlinks")
@include("instructions")
