@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")
@include("addon-toggles")
@include("service")

COPY packetbeat.yml.tmpl /usr/local/share/packetbeat.yml.tmpl

@include("packetbeat")

ENV ELASTICSEARCH_HOST="elasticsearch" \
    ELASTICSEARCH_PORT="9200"

VOLUME /backup/${IMAGE}/data

@include("copy-metadata")
@include("symlinks")
@include("instructions")
