@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

RUN mkdir -p /etc/service/${IMAGE}
COPY service /etc/service/${IMAGE}/run

RUN ${APTGET_INSTALL} -y mediatomb && \
    cd /etc/mediatomb && \
    mv config.xml config.xml.official && \
    chmod +x /etc/service/${IMAGE}/run

COPY config.xml /etc/mediatomb/config.xml

RUN chown -R mediatomb:mediatomb /etc/mediatomb

VOLUME /media

EXPOSE 49152

@include("copy-metadata")
@include("instructions")
