@include("preamble")
FROM ${NAMESPACE}/java:${TAG}
@include("maintainer")

@include("addon-toggles")

RUN ${SYSTEM_UPDATE} && \
    ${PKG_INSTALL} puppet-common puppet mcollective-common && \
    ${SYSTEM_CLEANUP}

COPY facts.sh /usr/local/bin/facts.sh
RUN chmod +x /usr/local/bin/facts.sh
COPY facts.cron /etc/cron.d/facts.sh

@include("copy-metadata")
@include("symlinks")
@include("instructions")
