# ${NAMESPACE}/${REPO}:${TAG} Dockerfile (generated at ${DATE})
FROM ${NAMESPACE}/java:${TAG}
MAINTAINER ${MAINTAINER}

# From Learning MCollective
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y puppet-common puppet mcollective-common

COPY facts.sh /usr/local/bin/facts.sh
RUN chmod +x /usr/local/bin/facts.sh
COPY facts.cron /etc/cron.d/facts.sh

COPY Dockerfile /Dockerfiles/${NAMESPACE}-${REPO}.${TAG}
