#!/bin/bash

if [ ! -e /README ]; then
    echo "Error: This image should include a README file."
    exit 1
fi

if [ "${1}" == "bash" ]; then
    shift;
    bash $*;
else
  for s in /etc/my_exec.d/*; do
    source $s
  done

  if [ -e /etc/my_exec.d/help ]; then
      source /etc/my_exec.d/help
      trap 'run_help' ERR
  fi

  $*
fi
