@include("preamble")
FROM ${REGISTRY}/${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")
@include("addon-toggles")
@include("service_user")
@include("gosu")
@include("tini")
@include("elk-common")
@include("kibana")
@include("service")

EXPOSE 5601

@include("copy-metadata")
@include("symlinks")
@include("instructions")
