@include("preamble")
FROM ${REGISTRY}/${NAMESPACE}/base:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

@include("service_user")
@include("gosu")
@include("tini")
@include("elk-common")
@include("kibana")

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE}
COPY service /etc/service/${IMAGE}/run
RUN chmod +x /etc/service/${IMAGE}/run

CMD ["kibana"]

@include("copy-metadata")
@include("symlinks")
@include("instructions")
