# ${NAMESPACE}/${REPO}:${TAG} Dockerfile (generated at ${DATE})
FROM ${ROOT_IMAGE}

MAINTAINER ${MAINTAINER}

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir -p /var/lib/apt/lists/partial

RUN apt-get -y update && apt-get install -y iptables facter

RUN cd /bin && rm -f /bin/sh && ln -s /bin/bash sh

CMD ["/sbin/my_init"]

COPY Dockerfile /Dockerfiles/${NAMESPACE}-${REPO}.${TAG}
