@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")
@include("gui")
@include("service_user")
@include("runme")
@include("pip")

RUN cd /opt && git clone --recursive  git://github.com/alicevision/meshroom && cd meshroom
RUN pip install -r requirements.txt
RUN rm -f /sbin/my_exec && ln -s /usr/local/bin/runme /sbin/my_exec && chmod +x /usr/local/bin/runme

@include("copy-metadata")
@include("symlinks")
@include("instructions")
