defineEnvVar PARENT_IMAGE_TAG "The tag of the base image" "201611";
defineEnvVar GRADLE_VERSION "The Gradle version" "3.2.1";
overrideEnvVar TAG '${GRADLE_VERSION}';
defineEnvVar WORKSPACE "The workspace folder" "/work";
overrideEnvVar ENABLE_LOGSTASH 'false';
defineEnvVar SERVICE_USER "The user account" "${NAMESPACE}";
defineEnvVar SERVICE_GROUP "The group" "users";
defineEnvVar SERVICE_USER_HOME "The home of the service user" '/home/${SERVICE_USER}';
defineEnvVar SERVICE_USER_SHELL "The shell of the service user" '/bin/bash';
defineEnvVar DEFAULT_DOCKER_API_VERSION "The docker API version" "1.23";
