defineEnvVar PARENT_IMAGE_TAG "The tag of the parent image" "201702";
defineEnvVar PROMETHEUS_VERSION "The Prometheus version" '1.5.0';
overrideEnvVar TAG '${PROMETHEUS_VERSION}';
defineEnvVar PROMETHEUS_FOLDER "The Prometheus folder" 'prometheus-${PROMETHEUS_VERSION}.linux-amd64';
defineEnvVar PROMETHEUS_ARTIFACT "The Prometheus artifact" '${PROMETHEUS_FOLDER}.tar.gz';
defineEnvVar PROMETHEUS_DOWNLOAD_URL "The Prometheus download url" 'https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/${PROMETHEUS_ARTIFACT}';
defineEnvVar SERVICE_USER "The Prometheus service user" "prometheus";
defineEnvVar SERVICE_GROUP "The Prometheus service group" "prometheus";
defineEnvVar SERVICE_USER_SHELL "The Prometheus account shell" "/bin/bash";
defineEnvVar SERVICE_USER_HOME "The Prometheus account home" "/opt/prometheus";
