@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("gui")
@include("service_user")

@include("openjdk")
@include("pharo")
@include("sdkman")
@include("gradle")
@include("gtoolkit")
@include("git")

#COPY git-files/gitconfig ${SERVICE_USER_HOME}/.gitconfig

#VOLUME ${SERVICE_USER_HOME}/.gradle

@include("copy-metadata")
@include("symlinks")
@include("instructions")

USER ${SERVICE_USER}
WORKDIR ${SERVICE_USER_HOME}/work

ENTRYPOINT /bin/bash
