@include("preamble")
FROM ${NAMESPACE}/java:${TAG}
@include("maintainer")

@include("addon-toggles")

COPY liquibase.sh /usr/local/bin/liquibase

ENTRYPOINT [ "/usr/local/bin/liquibase" ]

RUN mkdir /opt/liquibase-${LIQUIBASE_VERSION} && \
    cd /opt && \
    ln -s liquibase-${LIQUIBASE_VERSION} liquibase && \
    wget ${LIQUIBASE_URL} && \
    tar xvf ${LIQUIBASE_ARTIFACT} -C /opt/liquibase && \
    chmod +x /usr/local/bin/liquibase

@include("copy-metadata")
@include("instructions")