# ${NAMESPACE}/${REPO}:${TAG} Dockerfile (generated at ${DATE})
FROM ${BASE_IMAGE}:${TAG}
MAINTAINER ${MAINTAINER}

COPY rc.local /etc/rc.local
COPY watch_module_changes.sh /usr/local/bin/watch_module_changes.sh

RUN \
  DEBIAN_FRONTEND=noninteractive \
  apt-get install -y apache2 apache2-dev apache2-utils libtool && \
  mkdir /usr/local/lib/apache2 && \
  chmod +x /etc/rc.local /usr/local/bin/watch_module_changes.sh

VOLUME ["/var/www", "/usr/local/lib/apache2"]

EXPOSE 80

COPY Dockerfile /Dockerfiles/${NAMESPACE}-${REPO}.${TAG}

# Run with
# cd [apache-module-workdir];
# docker run -d -p [port]:80 -v $PWD:/usr/local/lib/apache2 ${NAMESPACE}/${REPO}-${STACK}
