# ${NAMESPACE}/${IMAGE}:${TAG} Dockerfile (generated at ${DATE})
FROM ${NAMESPACE}/apache:${TAG}
MAINTAINER ${MAINTAINER}

COPY enable-local-modules.sh /etc/my_init.d/50_enable_apache_extra_modules.sh
COPY watch_module_changes.sh /usr/local/bin/watch_module_changes.sh

RUN ${APTGET_INSTALL} apache2-dev apache2-utils libtool && \
    mkdir /usr/local/lib/apache2 && \
    chmod +x /usr/local/bin/watch_module_changes.sh && \
    chmod +x /etc/my_init.d/50_enable_apache_extra_modules.sh

VOLUME ["/var/www", "/usr/local/lib/apache2"]

COPY README /README
COPY Dockerfile /Dockerfiles/Dockerfile
COPY Dockerfile /Dockerfiles/${NAMESPACE}-${IMAGE}.${TAG}

# For instructions on how to use this image, please run
# docker run -it ${NAMESPACE}/${IMAGE}:${TAG} help
