@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

COPY rc.local /etc/rc.local

RUN ${APTGET_INSTALL} install python2.7 git-core python-m2crypto && \
    mkdir /var/www && \
    cd /var/www && git clone https://github.com/learningequality/ka-lite.git && \
    cd ka-lite && scripts/runatboot.sh && \
    chmod +x /etc/rc.local 

VOLUME /var/www/ka-lite

EXPOSE 8008

@include("copy-metadata")
@include("instructions")

