@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

@include("service_user")

@include("anaconda")

ENV PATH=${PATH}:${SERVICE_USER_HOME}/bin

WORKDIR ${SERVICE_USER_HOME}

@include("copy-metadata")
@include("symlinks")
@include("instructions")
@include("entrypoint")
@include("image_user")
