@include("preamble")
FROM ${NAMESPACE}/apache:${TAG}
@include("maintainer")

@include("addon-toggles")

COPY rc.local /etc/rc.local

RUN chmod +x /etc/rc.local

@include("copy-metadata")
@include("instructions")