@include("preamble")
FROM ${NAMESPACE}/java:${TAG}
@include("maintainer")

@include("addon-toggles")

RUN ${APTGET_INSTALL} zip && \
    ${APTGET_CLEANUP} && \
    rm -f /etc/my_init.d/* && \
    useradd -m -u ${DEVELOPMENT_USER_ID} -c "Development user" -U ${NAMESPACE}

USER ${NAMESPACE}

RUN cd /home/${NAMESPACE} && \
    wget -q -O- http://get.sdkman.io | bash && \
    chmod +x /home/${NAMESPACE}/.sdkman/bin/sdkman-init.sh

@include("copy-metadata")
@include("instructions")
