@include("preamble")
FROM ${REGISTRY}/${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

ENV DOBACKUP="true" \
    BACKUP_HOST_SSH_PORT="${BACKUP_HOST_SSH_PORT}"

@include("service_user")
#@include("create_ssl_certificate")
@include("mongodb")
#@include("filebeat")

COPY mongodb-files/service /etc/service/mongodb/run

RUN chmod +x /etc/service/mongodb/run

VOLUME /backup/${IMAGE}/db

@include("copy-metadata")
@include("symlinks")
@include("instructions")
