defineEnvVar SSL_CERTIFICATE_ALIAS "The alias of the SSL certificate" "";
defineEnvVar SSL_KEY_ALGORITHM "The algorithm of the SSL key pairs" "rsa";
defineEnvVar SSL_KEY_FOLDER "The folder storing the SSL key pairs" "/etc/ssl/private";
defineEnvVar SSL_KEYSTORE_NAME "The keystore name" "${SSL_KEYSTORE_NAME}";
defineEnvVar SSL_KEYSTORE_PASSWORD "The keystore password" "nmGEQlbT2qnCrBsfQDGFkygj8exgEmTCvmc1KSQ8VebBh5";
defineEnvVar SSL_KEY_PASSWORD "The key password" "K8emqG04hZKlOUY3rET1ZBChtqFuERxyWAtyVtnVrP1MYMXhA8SPhdBJ";
defineEnvVar SSL_CERTIFICATE_DNAME "The DName of the SSL certificate" "${SSL_CERTIFICATE_DNAME}";
defineEnvVar SSL_SIGN_ALGORITHM "The algorithm used to sign the SSL certificate" "${SSL_SIGN_ALGORITHM}";
defineEnvVar SSL_SAN_EXTENSIONS "The SAN extensions for the SSL certificate" "${SSL_SAN_EXTENSIONS}";
";
