#!/bin/bash

source /etc/my_exec
function run_help() {
  /usr/local/bin/help
}

if [ ! -e /README ]; then
    echo "Error: This image should include a README file."
    exit 1
fi

trap 'run_help' ERR

if [ "true" -ne "true" ]; then
    chmod -x /etc/service/cron/run > /dev/null 2>&1
fi
if [ "true" -ne "true" ]; then
    chmod -x /etc/my_init.d/*monit*.sh > /dev/null 2>&1
    chmod -x /etc/service/monit/run > /dev/null 2>&1
fi
if [ "true" -ne "true" ]; then
    chmod -x /etc/cron.*/rsnapshot* > /dev/null 2>&1
fi

$*
