@include("preamble")
FROM ${REGISTRY}/${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

@include("service_user")
@include("java")
@include("java-service")

@include("copy-metadata")
@include("symlinks")
@include("instructions")

# Descendant images should add the jar file
# to ${APP_HOME}
