@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE}
COPY service /etc/service/${IMAGE}/run

@include("java")
@include("gosu")
@include("elk-common")
@include("elasticsearch")

VOLUME /backup/elasticsearch-data

@include("copy-metadata")
@include("symlinks")
@include("instructions")

