@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

ENV DOBACKUP="false" \
    DISPLAY=":0"

@include("addon-toggles")

RUN ${SYSTEM_UPDATE} && \
    ${PKG_INSTALL} x11-apps && \
    ${SYSTEM_CLEANUP}

# COPY prepare.sh /usr/local/bin/prepare.sh

@include("copy-metadata")
@include("symlinks")
@include("instructions")
