@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

ENV DOBACKUP="false" \
    DISPLAY=":0"

@include("addon-toggles")

RUN ${APTGET_INSTALL} x11-apps && \
    ${APTGET_CLEANUP}

@include("copy-metadata")
@include("symlinks")
@include("instructions")
