defineEnvVar RIEMANN_VERSION "The version of Riemann" '0.2.11';
defineEnvVar RIEMANN_ARTIFACT "The Riemann artifact" 'riemann_${RIEMANN_VERSION}_all.deb';
defineEnvVar RIEMANN_URL "The url of the Riemann artifact" 'https://aphyr.com/riemann/${RIEMANN_ARTIFACT}';
overrideEnvVar TAG '${RIEMANN_VERSION}';
defineEnvVar RIEMANN_DIGEST "The md5 of the Riemann artifact" '8f074b9ad3321a962d3a32a7a54cf930';
defineEnvVar PARENT_IMAGE_TAG "The tag of the parent image" '201701';
defineEnvVar SERVICE_USER "The Riemann user" "riemann";
defineEnvVar SERVICE_GROUP "The Riemann group" "riemann";
defineEnvVar SERVICE_USER_HOME "The home of Riemann user" "/opt/riemann";
defineEnvVar SERVICE_USER_SHELL "The shell of Riemann user" "/bin/bash";
