@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

RUN cd /tmp && \
    wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb && \
    dpkg -i puppetlabs-release-trusty.deb && \
    ${APTGET_INSTALL} --update && \
    ${APTGET_CLEANUP}

@include("copy-metadata")
@include("instructions")