@include("preamble")
FROM ${NAMESPACE}/liquibase:${TAG}
@include("maintainer")

@include("addon-toggles")

COPY liquibase.sh /usr/local/bin/liquibase

RUN cd /opt/liquibase/lib && \
    wget ${POSTGRESQL_JDBC_DRIVER_URL} && \
    chmod +x /usr/local/bin/liquibase

@include("copy-metadata")
@include("instructions")
@include("symlinks")
