@include("preamble")
FROM ${NAMESPACE}/base-gui:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")
@include("gui")
@include("service_user")
@include("java")
@include("gui")
@include("studio3t")
@include("runme")

RUN rm -f /sbin/my_exec && ln -s /usr/local/bin/runme /sbin/my_exec && chmod +x /usr/local/bin/runme

@include("copy-metadata")
@include("symlinks")
@include("instructions")
