@include("preamble")
FROM ${BASE_IMAGE}:${BASE_TAG}
@include("maintainer")

@include("addon-toggles")

COPY my_exec /sbin/my_exec

ENV DOBACKUP="false" \
    SERVICE_USER="${SERVICE_USER}" \
    SERVICE_GROUP="${SERVICE_GROUP}"

RUN chmod +x /sbin/my_exec

@include("service_user")
@include("nodejs")

VOLUME [ "/opt/workspace" ]
WORKDIR /opt/workspace

@include("copy-metadata")
@include("symlinks")
@include("instructions")
