@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

# From https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions
RUN curl --silent --location --location https://deb.nodesource.com/setup_0.12 | bash - && \
    ${APTGET_INSTALL} nodejs && \
    ${APTGET_CLEANUP}

@include("copy-metadata")
@include("instructions")