defineEnvVar PARENT_IMAGE_TAG "The version of the parent image" "0.9.22";
defineEnvVar UBUNTU_VERSION "The version available in Ubuntu" "$(docker run --rm -it ${REGISTRY}/${NAMESPACE}/base:${PARENT_IMAGE_TAG} remote-ubuntu-version mysql-server | sed 's/[^0-9a-zA-Z\._-]//g')";
overrideEnvVar TAG '${UBUNTU_VERSION}';
defineEnvVar MYSQL_ROOT_PASSWORD "The password for the root user" "${RANDOM_PASSWORD}";
defineEnvVar MYSQL_ADMIN_USER "The admin user" "dbadmin";
defineEnvVar MYSQL_ADMIN_PASSWORD "The password for the admin user" "${RANDOM_PASSWORD}";
defineEnvVar MYSQL_ADMIN_PRIVILEGES "The default privileges for the admin user" "ALL PRIVILEGES";
defineEnvVar INNODB_DEFAULT_POOL_SIZE_FACTOR "The default pool size factor for InnoDB" "0.4";
defineEnvVar SERVICE_USER "The service user" "mysql";
defineEnvVar SERVICE_USER_PASSWORD "The password of the service user" "${RANDOM_PASSWORD}";
defineEnvVar SERVICE_GROUP "The service group" "mysql";
defineEnvVar SERVICE_USER_HOME "The home of the service user" '/backup/${IMAGE}';
defineEnvVar SERVICE_USER_SHELL "The shell of the service user" "/bin/bash";
overrideEnvVar ENABLE_CRON false;
overrideEnvVar ENABLE_MONIT true;
overrideEnvVar ENABLE_RSNAPSHOT false;
overrideEnvVar ENABLE_SYSLOG true;
overrideEnvVar ENABLE_LOGSTASH true;
