#!/bin/bash

_sleep=10;

_datadir=/backup/mysql-db
_rescode=0;
if [[ ! -e ${_datadir}/.bootstrapped ]]; then
    /usr/local/bin/bootstrap-db.sh -vv
    _rescode=$?;
    echo "boostrap returned ${_rescode}";
  while [ ! -e ${_datadir}/.bootstrapped ]; do
    echo "Waiting ${_sleep}s for db bootstrap"
    sleep ${_sleep}
  done
fi

chmod 755 ${_datadir}
chown -R mysql:mysql ${_datadir}

_poolSize=$(cat /proc/meminfo | grep MemTotal | awk -v f=${INNODB_POOL_SIZE_FACTOR:-0.4} '{printf("%s*%s*1024\n", $2, f);}' | bc -l | cut -d'.' -f 1)
[[ -d /usr/local/etc/mysql ]] && rsync -az /etc/mysql/conf.d/* /usr/local/etc/mysql && cp /usr/local/etc/mysql/*.cnf /etc/mysql/conf.d/
#[[ "${DISABLE_STRICT_MODE}" == "true" ]] && rm -f /etc/mysql/conf.d/mysqld_strict_mode.cnf
#[[ "${ALTERNATE_BOOLEAN_SYNTAX}" == "true" ]] && rm -f /etc/mysql/conf.d/mysqld_alternate_boolean_syntax.cnf

cat <<EOF > /etc/mysql/conf.d/mysqld_innodb_buffer_pool_size.cnf
[mysqld]
innodb_buffer_pool_size=${_poolSize}
EOF

rsync -az /etc/mysql/conf.d/ /var/local/mysql/conf.d/
rsync -az /var/local/mysql/conf.d/ /etc/mysql/conf.d/

mkdir /var/run/mysql
chown -R mysql:mysql /var/run/mysql

exec 2>&1
if [ "true" == "true" ]; then
    exec /usr/bin/mysqld_safe --console --user=mysql | logstash agent -f /etc/logstash/conf.d/mysql.conf
else
  exec /usr/bin/mysqld_safe --console --user=mysql \
      || mysqladmin -u root --password="${SQ_MYSQL_ROOT_PASSWORD}" -h127.0.0.1 --protocol=tcp shutdown
fi

