@include("preamble")
FROM ${NAMESPACE}/jenkins:${TAG}
@include("maintainer")

@include("addon-toggles")

ENV DOBACKUP="false"

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE}
COPY service /etc/service/${IMAGE}/run
RUN chmod +x /etc/service/${IMAGE}/run

COPY 41_jenkinsfile_to_pipeline_job.sh 41_jenkinsfile_to_pipeline_job.inc.sh \
     /etc/my_init.d/

VOLUME /workspace

@include("copy-metadata")
@include("instructions")
@include("symlinks")
