@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE}
COPY service /etc/service/${IMAGE}/run
RUN chmod +x /etc/service/${IMAGE}/run
COPY logstash.conf /etc/logstash/conf.d/${IMAGE}.conf

RUN ${APTGET_INSTALL} --update puppetmaster && \
    ${APTGET_CLEANUP}

@include("copy-metadata")
@include("instructions")
