defineEnvVar SSL_CERTIFICATE_ALIAS "The alias of the SSL certificate" "${SSL_CERTIFICATE_ALIAS}";
defineEnvVar SSL_KEY_ALGORITHM "The algorithm of the SSL key pairs" "${SSL_KEY_ALGORITHM}";
defineEnvVar SSL_KEY_LENGTH "The length of the SSL key" "${SSL_KEY_LENGTH}";
defineEnvVar SSL_KEY_FOLDER "The folder storing the SSL key pairs" "${SSL_KEY_FOLDER}";
defineEnvVar SSL_KEY_PASSWORD "The key password" "${SSL_KEY_PASSWORD}";
defineEnvVar SSL_CERTIFICATE_SUBJECT "The subject of the SSL certificate" "${SSL_CERTIFICATE_SUBJECT}";
defineEnvVar SSL_CERTIFICATE_EXPIRATION_DAYS "The number of days until the certificate expires" "${SSL_CERTIFICATE_EXPIRATION_DAYS}";
defineEnvVar SSL_KEY_ENCRYPTION "The encryption scheme for the key" "aes256";

defineEnvVar SSL_CERTIFICATE_ALIAS "The alias of the SSL certificate" "${SQ_SSL_CERTIFICATE_ALIAS}";
defineEnvVar SSL_KEY_ALGORITHM "The algorithm of the SSL key" "${SQ_SSL_KEY_ALGORITHM}";
defineEnvVar SSL_KEY_LENGTH "The length of the SSL key" "${SQ_SSL_KEY_LENGTH}";
defineEnvVar SSL_KEY_FOLDER "The folder storing the SSL key pairs" "${SQ_KEY_FOLDER}";
defineEnvVar SSL_KEY_PASSWORD "The key password" "${SQ_SSL_KEY_PASSWORD}";
defineEnvVar SSL_CERTIFICATE_COMMON_NAME "The common name for the SSL certificate" "${SQ_SSL_CERTIFICATE_COMMON_NAME}";
defineEnvVar SSL_CERTIFICATE_ORGANIZATIONAL_UNIT "The organizational unit for the SSL certificate" "${SQ_SSL_CERTIFICATE_ORGANIZATIONAL_UNIT}";
defineEnvVar SSL_CERTIFICATE_ORGANIZATION "The organization behind the SSL certificate" "${SQ_SSL_CERTIFICATE_ORGANIZATION}";
defineEnvVar SSL_CERTIFICATE_LOCALITY "The locality information in the SSL certificate" "${SQ_SSL_CERTIFICATE_LOCALITY}";
defineEnvVar SSL_CERTIFICATE_STATE "The state information in the SSL certificate" "${SQ_SSL_CERTIFICATE_STATE}";
defineEnvVar SSL_CERTIFICATE_COUNTRY "The country information in the SSL certificate" "${SQ_SSL_CERTIFICATE_COUNTRY}";
defineEnvVar SSL_CERTIFICATE_SUBJECT "The subject of the SSL certificate" "${SQ_SSL_CERTIFICATE_SUBJECT}";
defineEnvVar SSL_CERTIFICATE_DNAME "The DName of the SSL certificate" "${SQ_SSL_CERTIFICATE_DNAME}";
defineEnvVar SSL_CERTIFICATE_EXPIRATION_DAYS "The number of days until the certificate expires" "${SQ_SSL_CERTIFICATE_EXPIRATION_DAYS}";
defineEnvVar SSL_KEYSTORE_FOLDER "The folder storing the SSL keystore" "${SQ_SSL_KEYSTORE_FOLDER}";
defineEnvVar SSL_KEYSTORE_PATH "${SQ_SSL_KEYSTORE_PATH}";
defineEnvVar SSL_KEYSTORE_NAME "The keystore name" "${SQ_SSL_KEYSTORE_NAME}";
defineEnvVar SSL_KEYSTORE_PASSWORD "The keystore password" "${SQ_SSL_KEYSTORE_PASSWORD}";
defineEnvVar SSL_JAVA_SIGN_ALGORITHM "The algorithm used to sign the SSL certificate" "${SQ_SSL_JAVA_SIGN_ALGORITHM}";
defineEnvVar SSL_SAN_EXTENSIONS "The SAN extensions for the SSL certificate" "${SQ_SSL_SAN_EXTENSIONS}";
