defineEnvVar SSL_KEY_ALGORITHM "The algorithm of the SSL key" "${SQ_SSL_KEY_ALGORITHM:-rsa}";
defineEnvVar SSL_KEY_LENGTH "The length of the SSL key" "${SQ_SSL_KEY_LENGTH:-2048}";
defineEnvVar SSL_KEY_ENCRYPTION "The encryption scheme for the key" "aes256";
defineEnvVar SSL_KEY_FOLDER "The folder storing the SSL key pairs" "${SQ_SSL_KEY_FOLDER:-/etc/ssl/private}";
defineEnvVar SSL_KEY_PASSWORD "The key password" "${SQ_SSL_KEY_PASSWORD:-${SQ_NAMESPACE:-acmsl}-${SQ_IMAGE:-base}}";
defineEnvVar SSL_KEYSTORE_FOLDER "The folder storing the SSL keystore" "${SQ_SSL_KEYSTORE_FOLDER:-/etc/ssl/private}";
defineEnvVar SSL_KEYSTORE_NAME "The keystore name" "${SQ_SSL_KEYSTORE_NAME:-${SQ_IMAGE:-base}}";
defineEnvVar SSL_KEYSTORE_PATH "The keystore path" "${SQ_SSL_KEYSTORE_PATH:-${SSL_KEYSTORE_PATH}}";
defineEnvVar SSL_KEYSTORE_TYPE "The type of the keystore" "${SQ_SSL_KEYSTORE_TYPE:-jks}";
defineEnvVar SSL_KEYSTORE_PASSWORD "The keystore password" "${SQ_SSL_KEYSTORE_PASSWORD:-${SQ_NAMESPACE:-acmsl}-${SQ_IMAGE:-base}}";
defineEnvVar SSL_CERTIFICATE_ALIAS "The alias of the SSL certificate" "${SQ_IMAGE:-base}";
defineEnvVar SSL_CERTIFICATE_COMMON_NAME "The common name for the SSL certificate" '${SQ_IMAGE:-base}.${SQ_DOMAIN:-=}';
defineEnvVar SSL_CERTIFICATE_WILDCARD_COMMON_NAME "The wildcard version of the common name for the SSL certificate" '*.${SQ_DOMAIN:-=}';
defineEnvVar SSL_CERTIFICATE_ORGANIZATIONAL_UNIT "The organizational unit for the SSL certificate" "${SQ_SSL_CERTIFICATE_ORGANIZATIONAL_UNIT:-IT}";
defineEnvVar SSL_CERTIFICATE_ORGANIZATION "The organization behind the SSL certificate" "${SQ_SSL_CERTIFICATE_ORGANIZATION:-=}";
defineEnvVar SSL_CERTIFICATE_LOCALITY "The locality information in the SSL certificate" "${SQ_SSL_CERTIFICATE_LOCALITY:-Madrid}";
defineEnvVar SSL_CERTIFICATE_STATE "The state information in the SSL certificate" "${SQ_SSL_CERTIFICATE_STATE:-Madrid}";
defineEnvVar SSL_CERTIFICATE_COUNTRY "The country information in the SSL certificate" "${SQ_SSL_CERTIFICATE_COUNTRY:-ES}";
defineEnvVar SSL_CERTIFICATE_SUBJECT "The subject of the SSL certificate" '/C=ES/ST=Madrid/L=Madrid/O==/OU=IT/CN=${SSL_CERTIFICATE_COMMON_NAME}';
defineEnvVar SSL_CERTIFICATE_DNAME "The DName of the SSL certificate" 'CN=${SSL_CERTIFICATE_WILDCARD_COMMON_NAME}, OU=IT, O==, L=Madrid, S=Madrid, C=ES';
defineEnvVar SSL_CERTIFICATE_EXPIRATION_DAYS "The number of days until the certificate expires" "${SQ_SSL_CERTIFICATE_EXPIRATION_DAYS:-3650}";
defineEnvVar SSL_JAVA_SIGN_ALGORITHM "The algorithm used to sign the SSL certificate" "${SQ_SSL_JAVA_SIGN_ALGORITHM:-SHA256withRSA}";
defineEnvVar SSL_SAN_EXTENSIONS "The SAN extensions for the SSL certificate" 'dns:${SSL_CERTIFICATE_COMMON_NAME},dns:*.${SSL_CERTIFICATE_COMMON_NAME},dns:*.${SQ_IMAGE:-base}.${SQ_DOMAIN:-=},dns:*.${SQ_DOMAIN:-=}';
