@include("preamble")
FROM ${REGISTRY}/${NAMESPACE}/base:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE}
COPY service /etc/service/${IMAGE}/run
RUN chmod +x /etc/service/${IMAGE}/run

@include("java")
@include("gosu")
@include("elk-common")
@include("logstash")

CMD ["-e", ""]

@include("copy-metadata")
@include("symlinks")
@include("instructions")
