@include("preamble")
FROM ${REGISTRY}/${NAMESPACE}/base:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

RUN mkdir /etc/service/${IMAGE} && cp -r /etc/service/.template/* /etc/service/${IMAGE}
#COPY service /etc/service/${IMAGE}/run
RUN chmod +x /etc/service/${IMAGE}/run

@include("java")
@include("logstash")

#EXPOSE 9200

#VOLUME /var/www

#@include("copy-metadata")
#@include("symlinks")
#@include("instructions")
