@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")
@include("service_user")
@include("pharo32b")
@include("pillar")
@include("runme")

RUN rm -f /sbin/my_exec && ln -s /etc/service/pharo/run /sbin/my_exec

ENTRYPOINT /usr/local/bin/runme

VOLUME [ "${SERVICE_USER_HOME}" ]

@include("copy-metadata")
@include("symlinks")
@include("instructions")
