@include("preamble")
FROM ${REGISTRY}/${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

ENV DOBACKUP="false" \
    SERVICE="apache-files/service"

@include("apache")
@include("service")

RUN rm -rf /var/www && \
    ln -s /backup/${IMAGE}-www /var/www

EXPOSE 80

VOLUME /backup/${IMAGE}-www

@include("copy-metadata")
@include("symlinks")
@include("instructions")

