#!/bin/bash

read pid cmd state ppid pgrp session tty_nr tpgid rest < /proc/self/stat
trap "kill -TERM -$pgrp; exit" EXIT TERM KILL SIGKILL SIGTERM SIGQUIT

source /etc/apache2/envvars

exec 2>&1
#exec apache2 -D FOREGROUND -D NO_DETACH | /opt/logstash/bin/logstash agent -f /etc/logstash/conf.d/apache2.conf -l /var/log/logstash/apache2.log
exec apache2 -D FOREGROUND -D NO_DETACH

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
