@include("preamble")
FROM ${BASE_IMAGE}:${TAG}
@include("maintainer")

@include("addon-toggles")

COPY my_exec /sbin/my_exec

COPY service /usr/local/bin/${IMAGE}
COPY service.inc.sh /usr/local/bin/${IMAGE}.inc.sh

RUN ${APTGET_INSTALL} postgresql-client && \
    ${APTGET_CLEANUP} && \
    chmod +x /sbin/my_exec && \
    chmod +x /usr/local/bin/${IMAGE} && \
    chmod -x /usr/local/bin/${IMAGE}.inc.sh

VOLUME /sql

@include("copy-metadata")
@include("symlinks")
@include("instructions")
