@include("preamble")
FROM ${BASE_IMAGE}:${PARENT_IMAGE_TAG}
@include("maintainer")

@include("addon-toggles")

COPY my_exec /sbin/my_exec

COPY service /usr/local/bin/${IMAGE}

ENV SERVICE_PACKAGE="mariadb-client" \
    SERVICE_USER="mysql" \
    SERVICE_GROUP="mysql";

@include("mariadb-bootstrap")

VOLUME /sql

@include("copy-metadata")
@include("symlinks")
@include("instructions")
