defineEnvVar PARENT_IMAGE_TAG "The tag of the parent image" "201702";
defineEnvVar APP_HOME "The application home" "/opt/grails";
defineEnvVar SERVICE_USER "The service user" "grails";
defineEnvVar SERVICE_GROUP "The service group" "grails";
defineEnvVar SERVICE_USER_HOME "The home of the service user" '${APP_HOME}';
defineEnvVar SERVICE_USER_SHELL "The shell of the service user" "/bin/bash";
defineEnvVar DEFAULT_LOCALE "The default locale" "en_US";
defineEnvVar DEFAULT_ENCODING "The default encoding" "UTF-8";
defineEnvVar DEFAULT_JAVA_OPTS "The default JAVA_OPTS" "";
overrideEnvVar ENABLE_CRON 'false';
overrideEnvVar ENABLE_RSNAPSHOT 'false';
overrideEnvVar ENABLE_MONIT 'false';
